// ── Shared dummy data for Workverra MVP ──────────────────────────────────────

export const SKILLS_LIST = [
  'Electrician', 'Plumber', 'Carpenter', 'Painter', 'Mason',
  'Welder', 'AC Technician', 'Tiler', 'Roofer', 'Gardener',
  'Security Guard', 'Driver', 'Cook', 'Housekeeper', 'Labourer',
  'IT Support', 'CCTV Technician', 'Packers & Movers', 'Pest Control', 'Fabricator',
]

export const CITIES = [
  'Indore', 'Bhopal', 'Jabalpur', 'Gwalior', 'Ujjain',
  'Raipur', 'Bilaspur', 'Nagpur', 'Aurangabad', 'Nashik',
  'Surat', 'Rajkot', 'Vadodara', 'Jaipur', 'Jodhpur',
  'Kota', 'Udaipur', 'Patna', 'Ranchi', 'Varanasi',
  'Agra', 'Meerut', 'Lucknow', 'Kanpur', 'Allahabad',
  'Dehradun', 'Haridwar', 'Chandigarh', 'Ludhiana', 'Amritsar',
]

export const workers = [
  {
    id: 'w1',
    initials: 'MK',
    name: 'Mohan Kumar',
    skill: 'Plumber',
    skills: ['Pipe Fitting', 'Leakage Fix', 'Bathroom Setup', 'Water Tank'],
    experience: 6,
    city: 'Indore',
    pinCode: '452001',
    rating: 4.9,
    totalReviews: 89,
    hourlyRate: 380,
    jobsDone: 120,
    verified: true,
    badge: null,
    available: true,
    avatarGradient: 'linear-gradient(135deg,#667eea,#764ba2)',
    about: 'Expert plumber with 6+ years in residential and commercial projects across Indore. Specialised in modern bathroom fittings and emergency repairs.',
    joinedDate: 'Jan 2023',
    responseTime: '< 1 hour',
    successRate: '98%',
  },
  {
    id: 'w2',
    initials: 'PS',
    name: 'Priya Sharma',
    skill: 'Painter',
    skills: ['Wall Painting', 'Texture Work', 'Waterproofing', 'Polish', 'Stencil'],
    experience: 8,
    city: 'Bhopal',
    pinCode: '462001',
    rating: 4.8,
    totalReviews: 134,
    hourlyRate: 520,
    jobsDone: 210,
    verified: true,
    badge: 'Top Rated Pro',
    available: true,
    avatarGradient: 'linear-gradient(135deg,#f093fb,#f5576c)',
    about: 'Professional painter known for premium texture and decorative finishes. 8 years experience with both interior and exterior projects.',
    joinedDate: 'Mar 2022',
    responseTime: '< 2 hours',
    successRate: '99%',
  },
  {
    id: 'w3',
    initials: 'AV',
    name: 'Amit Verma',
    skill: 'Carpenter',
    skills: ['Furniture Making', 'Door Fitting', 'Modular Kitchen', 'Wood Polish'],
    experience: 4,
    city: 'Jabalpur',
    pinCode: '482001',
    rating: 4.5,
    totalReviews: 56,
    hourlyRate: 290,
    jobsDone: 78,
    verified: true,
    badge: null,
    available: false,
    avatarGradient: 'linear-gradient(135deg,#4facfe,#00f2fe)',
    about: 'Skilled carpenter specialising in custom furniture and modular kitchen installations.',
    joinedDate: 'Jun 2023',
    responseTime: '< 3 hours',
    successRate: '94%',
  },
  {
    id: 'w4',
    initials: 'RJ',
    name: 'Rakesh Joshi',
    skill: 'Electrician',
    skills: ['Wiring', 'Panel Work', 'AC Repair', 'Inverter Setup', 'CCTV'],
    experience: 10,
    city: 'Indore',
    pinCode: '452010',
    rating: 4.7,
    totalReviews: 203,
    hourlyRate: 450,
    jobsDone: 310,
    verified: true,
    badge: 'Expert',
    available: true,
    avatarGradient: 'linear-gradient(135deg,#f6d365,#fda085)',
    about: 'Senior electrician with a decade of experience in residential, commercial, and industrial electrical work.',
    joinedDate: 'Nov 2021',
    responseTime: '< 30 min',
    successRate: '99%',
  },
  {
    id: 'w5',
    initials: 'SK',
    name: 'Sunita Kumari',
    skill: 'Housekeeper',
    skills: ['Deep Cleaning', 'Cooking', 'Laundry', 'Childcare'],
    experience: 5,
    city: 'Gwalior',
    pinCode: '474001',
    rating: 4.6,
    totalReviews: 72,
    hourlyRate: 200,
    jobsDone: 145,
    verified: true,
    badge: null,
    available: true,
    avatarGradient: 'linear-gradient(135deg,#a18cd1,#fbc2eb)',
    about: 'Experienced housekeeper providing reliable and thorough home management services.',
    joinedDate: 'Aug 2022',
    responseTime: '< 2 hours',
    successRate: '97%',
  },
  {
    id: 'w6',
    initials: 'DN',
    name: 'Dinesh Nair',
    skill: 'AC Technician',
    skills: ['AC Installation', 'Gas Refill', 'Servicing', 'Split AC', 'Window AC'],
    experience: 7,
    city: 'Ujjain',
    pinCode: '456001',
    rating: 4.8,
    totalReviews: 117,
    hourlyRate: 500,
    jobsDone: 190,
    verified: true,
    badge: 'Top Rated Pro',
    available: true,
    avatarGradient: 'linear-gradient(135deg,#43e97b,#38f9d7)',
    about: 'Certified AC technician with expertise in all major brands. Fast turnaround and genuine spare parts guaranteed.',
    joinedDate: 'Feb 2022',
    responseTime: '< 1 hour',
    successRate: '98%',
  },
]

export const bookings = [
  {
    id: 'b1',
    workerId: 'w1',
    workerName: 'Mohan Kumar',
    workerSkill: 'Plumber',
    jobDescription: 'Bathroom pipe leakage fix',
    date: '2 Jun 2025',
    time: '10:00 AM',
    duration: 3,
    amount: 1140,
    status: 'completed',
    paymentStatus: 'released',
    rating: 5,
  },
  {
    id: 'b2',
    workerId: 'w4',
    workerName: 'Rakesh Joshi',
    workerSkill: 'Electrician',
    jobDescription: 'New wiring for 3 BHK flat',
    date: '8 Jun 2025',
    time: '09:00 AM',
    duration: 6,
    amount: 2700,
    status: 'confirmed',
    paymentStatus: 'held',
    rating: null,
  },
  {
    id: 'b3',
    workerId: 'w2',
    workerName: 'Priya Sharma',
    workerSkill: 'Painter',
    jobDescription: 'Living room texture painting',
    date: '15 Jun 2025',
    time: '11:00 AM',
    duration: 8,
    amount: 4160,
    status: 'pending',
    paymentStatus: 'unpaid',
    rating: null,
  },
  {
    id: 'b4',
    workerId: 'w3',
    workerName: 'Amit Verma',
    workerSkill: 'Carpenter',
    jobDescription: 'Wardrobe installation',
    date: '20 May 2025',
    time: '02:00 PM',
    duration: 4,
    amount: 1160,
    status: 'completed',
    paymentStatus: 'released',
    rating: 4,
  },
  {
    id: 'b5',
    workerId: 'w6',
    workerName: 'Dinesh Nair',
    workerSkill: 'AC Technician',
    jobDescription: 'AC gas refill + servicing',
    date: '5 Jun 2025',
    time: '03:00 PM',
    duration: 2,
    amount: 1000,
    status: 'rejected',
    paymentStatus: 'refunded',
    rating: null,
  },
]

export const reviews = [
  { id: 'r1', workerId: 'w1', employerName: 'Rahul Gupta', initials: 'RG', stars: 5, comment: 'Excellent work! Fixed the leakage very quickly and cleanly. Highly recommended.', date: '3 Jun 2025' },
  { id: 'r2', workerId: 'w1', employerName: 'Meena Patel', initials: 'MP', stars: 5, comment: 'Very professional. Arrived on time and did the job perfectly.', date: '28 May 2025' },
  { id: 'r3', workerId: 'w1', employerName: 'Suresh Agarwal', initials: 'SA', stars: 4, comment: 'Good work overall. Could improve communication.', date: '15 May 2025' },
]

export const notifications = [
  { id: 'n1', icon: '📋', message: 'Mohan Kumar accepted your plumbing booking for 8 Jun', time: '2 hours ago', read: false },
  { id: 'n2', icon: '💳', message: 'Payment of ₹2,700 held in escrow for Rakesh Joshi booking', time: '5 hours ago', read: false },
  { id: 'n3', icon: '✅', message: 'Job completed! Release payment to Mohan Kumar', time: 'Yesterday', read: false },
  { id: 'n4', icon: '⭐', message: 'Your review has been published. Thank you!', time: '2 days ago', read: true },
  { id: 'n5', icon: '🔔', message: 'New worker Dinesh Nair is now available in your area', time: '3 days ago', read: true },
]

// Worker-side notifications (incoming jobs)
export const workerNotifications = [
  { id: 'wn1', icon: '📋', message: 'New booking request from Rahul Gupta — Plumbing, 2 Jun', time: '1 hour ago', read: false },
  { id: 'wn2', icon: '💳', message: 'Payment of ₹1,140 released to your account!', time: '3 hours ago', read: false },
  { id: 'wn3', icon: '⭐', message: 'Meena Patel left you a 5-star review!', time: 'Yesterday', read: true },
  { id: 'wn4', icon: '🔔', message: 'Your profile views increased by 40% this week', time: '2 days ago', read: true },
]

export const formatCurrency = (amount) =>
  new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(amount)
